INSERT INTO category (name)
VALUES
    ('Electronics'),
    ('Furniture'),
    ('Clothing'),
    ('Books'),
    ('Beauty Products'),
    ('Toys'),
    ('Groceries'),
    ('Fitness Equipment'),
    ('Office Supplies'),
    ('Pet Supplies'),
    ('Automotive'),
    ('Jewelry'),
    ('Home Decor'),
    ('Gardening'),
    ('Kitchen Appliances'),
    ('Sports Gear'),
    ('Footwear'),
    ('Baby Products'),
    ('Musical Instruments'),
    ('Stationery'),
    ('Outdoor Equipment'),
    ('Health Products'),
    ('Smartphones'),
    ('Laptops'),
    ('Tablets'),
    ('Cameras'),
    ('Watches'),
    ('Art Supplies'),
    ('Bedding'),
    ('Cleaning Supplies'),
    ('Hobby Supplies'),
    ('Lighting'),
    ('Games'),
    ('Educational Materials'),
    ('Travel Accessories'),
    ('Camping Gear'),
    ('Party Supplies'),
    ('Safety Equipment'),
    ('Bicycles'),
    ('Tools'),
    ('Plumbing Supplies'),
    ('Car Accessories'),
    ('Motorcycle Gear'),
    ('Eyewear'),
    ('Cosmetics'),
    ('Perfumes'),
    ('Skincare'),
    ('Haircare'),
    ('Nutritional Supplements'),
    ('Cooking Utensils'),
    ('Baking Supplies'),
    ('Puzzles'),
    ('Board Games'),
    ('Computer Accessories'),
    ('Networking Equipment'),
    ('Printers'),
    ('Scanners'),
    ('Gaming Consoles'),
    ('Video Games'),
    ('Drones'),
    ('Robotics Kits'),
    ('3D Printers'),
    ('VR Headsets'),
    ('Fitness Trackers'),
    ('Smartwatches'),
    ('Energy Bars'),
    ('Tea & Coffee'),
    ('Kitchen Storage'),
    ('Laundry Supplies'),
    ('Seasonal Decorations'),
    ('Bookshelves'),
    ('Sofas'),
    ('Dining Tables'),
    ('Chairs'),
    ('Wardrobes'),
    ('Outdoor Furniture'),
    ('BBQ Grills'),
    ('Picnic Supplies'),
    ('Travel Bags'),
    ('Luggage'),
    ('School Bags'),
    ('Wallets'),
    ('Belts'),
    ('Hats'),
    ('Scarves'),
    ('Sunglasses'),
    ('Rainwear'),
    ('Winter Wear'),
    ('Swimwear'),
    ('Undergarments'),
    ('Wedding Supplies'),
    ('Craft Kits'),
    ('DIY Kits'),
    ('Art Prints'),
    ('Posters'),
    ('Gift Wrapping'),
    ('Greeting Cards'),
    ('Luxury Items'),
    ('Organic Products'),
    ('Eco-friendly Products'),
    ('Secondhand Goods');
